const { defineConfig } = require("cypress");
const { verifyDownloadTasks } = require("cy-verify-downloads");

module.exports = defineConfig({
  projectId: "xk3b1j",
  e2e: {
    setupNodeEvents(on, config) {
      on("task", verifyDownloadTasks);
    },
    baseUrl: "https://oksanabondar.stage-81y92gtmor.peopleforce.io/",
    viewportHeight: 1080,
    viewportWidth: 1920,
    defaultCommandTimeout: 10000,
    retries: 2,
    videoUploadOnPasses: false,
    chromeWebSecurity: false,
    experimentalModifyObstructiveThirdPartyCode: true,
    experimentalWebKitSupport: true,
    excludeSpecPattern: ["cypress/e2e/1_prepearingTenant/**.cy.js"],
    env: {
      baseUrl: "https://oksanabondar.stage-81y92gtmor.peopleforce.io/",
      username: "ksushenkabondar@gmail.com",
      password: "tester11",
      oldUserUrl: "https://yuliiabakurevych.stage-81y92gtmor.peopleforce.io/",
      oldUserName: "test.qa.new@mailsac.com",
      oldUserPassword: "Password1",
      secondUserName: "pf.qa.employee@mailsac.com",
      googleCalendarEmail: "andrew@pflocal.dev",
      microsoftOutlookEmail: "andrew@mspflocal.dev",
      integrationPassword: "H2v9Xqh@hiO&6kUvMl9IISYi%WJ",
      usernickname: "Andrew",
      username_wrong: "test@test.io",
      MAILOSAUR_API_KEY: "uXaSs5NKTzHoArxE",
      profile_name: "Cetinic Andrew",
      employee_profile_name: "Wicker John",
      company_name: "QA Automation",
      status_color_red: "rgb(254, 227, 219)",
      status_color_green: "rgb(207, 245, 222)",
      status_color_yellow: "rgb(249, 233, 179)",
      status_color_grey: "rgb(229, 236, 243)",
      errorBorderColor: "rgb(220, 53, 69)",
      acc_secondary_color: "rgb(0, 185, 80)",
      acc_primary_color: "rgb(13, 116, 188)",
      element_focused_color: "rgb(0, 0, 0)",
      x_api_key: "hyh8iacgjlX1EgRrOKBRxgtt_1",
      link_color: "rgb(44, 141, 255)",
      dateFormat: "DD.MM.YYYY",
      displayDateFormat: "MMM DD, YYYY",
      dateFormatWithTime: "DD.MM.YYYY HH:mm",
      dateFormatFullMonthWithTIme: "MMM DD, YYYY HH:mm",
      serverId: "gheto1qe",
      serverDomain: "gheto1qe.mailosaur.net",
      emailAddress: "mail@gheto1qe.mailosaur.net",
    },
  },
  reporter: "cypress-multi-reporters",
  reporterOptions: {
    reporterEnabled: "mocha-junit-reporter, cypress-qase-reporter",
    mochaJunitReporterReporterOptions: {
      mochaFile: "results/results-[hash].xml",
    },
    cypressQaseReporterReporterOptions: {
      apiToken: "e57bd4a906e0c3ed8f05165c9558b5f604ea9956",
      projectCode: "WEB",
      logging: true,
      runId: 459,
    },
    video: false,
  },
});
